apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: fake-api
  description: The apis.guru REST API
spec:
  type: openapi
  lifecycle: experimental
  owner: user:guest
  system: "fake"
  definition:
    $text: ./openapi.yaml

