apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fake-backstage
  description: A totally fake catalogue entry
  tags:
    - python
    - backend
  annotations:
    backstage.io/techdocs-ref: dir:.
    endoflife.date/products: django@3.2
spec:
  type: service
  lifecycle: experimental
  owner: user:default/guest
  dependsOn: 
    - Component:fake-library
  providesApis:
    - fake-api
  system: "fake"
