apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fake-backstage
  description: A totally fake catalogue entry
  tags:
    - python
    - backend
spec:
  type: service
  lifecycle: production
  owner: user:guest
